version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_username
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d