"""empty message

Revision ID: f86cb28c1874
Revises: b38c145193c9
Create Date: 2023-07-06 19:12:54.664440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86cb28c1874'
down_revision = 'b38c145193c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
